### ISSUE TITLE
ImportError on test data

### ISSUE THREAD

**Issue by paulstretenowich** [IHEC/intgerative_analysis_chip#1]
Hi @sitag,

I'm facing an `ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory` trying the pipeline on test data at steps idr and test_macs2.

You can find attached an exemple of the stderr file generated. [stderr.txt](https://github.com/IHEC/integrative_analysis_chip/files/3444049/stderr.txt)

Paul

**Comment by sitag** [comment]
what did you do to get that error? likely you are not using the container right, and pulling your local python.

**Comment by paulstretenowich** [comment]
As you recommended to do I followed https://github.com/IHEC/integrative_analysis_chip/blob/master/encode-wrapper/readme.md, using `get_encode_resources.sh` script to pull the resources. Then:
1. `$ python chip.py -get`
2. `$ python chip.py -pullimage -bindpwd`
3. `$ chmod +x ./*sh`
4. `$ ./singularity_encode_test_tasks.sh Local try1`

And facing the ImportError...

Paul

**Comment by sitag** [comment]
use anaconda latest python 2.7

**Comment by paulstretenowich** [comment]
I still have the same issue even using Anaconda2 release 2019.07.

**Comment by sitag** [comment]
can you run the IHEC tests for H3k4me3?

**Comment by sitag** [comment]
what version of singularity are you running?

**Comment by paulstretenowich** [comment]
I have the same error on the step call-fingerprint trying with H3k4me3 from IHEC. Cf. 
[stderr.txt](https://github.com/IHEC/integrative_analysis_chip/files/3457594/stderr.txt).

I'm using singularity version 3.2.

**Comment by sitag** [comment]
can you attach the full log of the command you ran, for the encode tests case. what os are you using?

**Comment by paulstretenowich** [comment]
I ran `./singularity_encode_test_tasks.sh Local try1 > encode_test.log 2>&1` for the test encode data set with the corresponding log file [encode_test.log.txt](https://github.com/IHEC/integrative_analysis_chip/files/3457862/encode_test.log.txt).

I'm on a Compute Canada server with Linux CentOS 7.

**Comment by sitag** [comment]
do you have a local install of idr on your path?

**Comment by sitag** [comment]
nothing has changed with the code and it works okay for me. i suspsect there's something in your environment. 

can you get a shell on your container with - 

singularity shell -B $PWD ./images/chip_seq_pipeline_v1_1_4.sif # or whatever is your image

and then do

which python
which idr
echo $PYTHONPATH

followed by the idr command that fails -

idr --samples /project/6008047/stretenp/IHEC/test/1_chipseq_ihec/integrative_analysis_chip/encode-wrapper/chip-seq-pipeline2/test/test_task/cromwell-executions/test_idr/6adb970e-dd5e-4dd6-9c7d-34cc4d35fa9a/call-se_idr/inputs/-1787404853/rep1.subsampled.25.merged.nodup_x_ctl1.subsampled.25.merged.nodup.pooled.300K.regionPeak.gz /project/6008047/stretenp/IHEC/test/1_chipseq_ihec/integrative_analysis_chip/encode-wrapper/chip-seq-pipeline2/test/test_task/cromwell-executions/test_idr/6adb970e-dd5e-4dd6-9c7d-34cc4d35fa9a/call-se_idr/inputs/-1787404852/rep2.subsampled.20.merged.nodup_x_ctl1.subsampled.25.merged.nodup.pooled.300K.regionPeak.gz --peak-list /project/6008047/stretenp/IHEC/test/1_chipseq_ihec/integrative_analysis_chip/encode-wrapper/chip-seq-pipeline2/test/test_task/cromwell-executions/test_idr/6adb970e-dd5e-4dd6-9c7d-34cc4d35fa9a/call-se_idr/inputs/408753520/rep1.subsampled.25.merged.nodup.pooled_x_ctl1.subsampled.25.merged.nodup.pooled.300K.regionPeak.gz --input-file-type narrowPeak --output-file rep1-rep2.idr0.1.unthresholded-peaks.txt --rank signal.value --soft-idr-threshold 0.1 --plot --use-best-multisummit-IDR --log-output-file rep1-rep2.idr0.1.log

make sure you are in encode_wrapper directory before you run singularity, so paths work. make sure your image is built with same version of singularity that you are running with.

**Comment by paulstretenowich** [comment]
I don't have a local idr installed.

When I'm in the singularity shell:
- `which python`: `/usr/bin/python`
- `which idr`: `/usr/local/bin/idr`
- `echo $PYTHONPATH`: `/cvmfs/soft.computecanada.ca/custom/python/site-packages`

When I run the `idr` command I have again the same error.

I'm in the encode-wrapper directory and I have built the singularity image with singularity version 3.2.1, the same version used for running.

**Comment by sitag** [comment]
unset your PYTHONPATH before running it. 
if that fails run it using the /ext/mnt0 approach described in readme. 
if that fails try running it using an older version of singularity - 3.0 and then 2.52+.
the singularity image is the same, the commands being run are the same, so something has changed in your environment.

**Comment by sitag** [comment]
can you also do echo $LD_LIBRARY_PATH on the image shell? 
if this is unset - i expect it should be, then this is your problem. don't need to do anything else. there's an easy fix. see https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/docker_image/Dockerfile#L46

**Comment by paulstretenowich** [comment]
When I `unset PYTHONPATH` I still have the same issue.
Using the /ext/mnt0 approach is not changing the issue.
Trying with singularity v2.6.1 works now but previously it didn't.
$LD_LIBRARY_PATH is set on the image either using singularity v3.2.1 or v2.6.1.
By now the only way to have it working on test data is using singularity v2.6.1.

**Comment by sitag** [comment]
what is LD_LIBRARY_PATH set to?

Can you modify the singularity_wrapper and the test task scripts to print out LD_LIBRARY_PATH when they run, so we can log what it's actually seeing?

mkl shared lib in on the image under /opt/intel/compilers_and_libraries_2018.0.128/linux/mkl/lib/intel64_lin soit should be able to find it.

**Comment by paulstretenowich** [comment]
The issue with LD_LIBRARY_PATH is because Singularity (at least since version 3.1.1) doesn't unset it. Cf. https://github.com/sylabs/singularity/issues/3510
To fix it you could replace `singularity exec` by `singularity exec --cleanenv` when calling the singularity image so that you are sure not to use some PATH inherited from outside the container?

**Comment by sitag** [comment]
looks like your pr fixed this. closing.
