### ISSUE TITLE
Raw bigwig files step

### ISSUE THREAD

**Issue by GFrosi** [IHEC/intgerative_analysis_chip#6]
Hi @sitag,

I would like to know if your group have an updated version of the ENCODE pipeline with the step related to generation of Raw bigwig files, or a code that could be shared to generate this file.

I am working with the files cloned from dev-organize-output branch. 

Thanks in advance for your help.

Gabriella Frosi

**Comment by sitag** [comment]
@GFrosi see https://github.com/IHEC/integrative_analysis_chip/blob/dev-organize-output/encode-wrapper/postprocess/postprocess.sh#L33 and
https://github.com/IHEC/integrative_analysis_chip/blob/dev-organize-output/encode-wrapper/postprocess/postprocess.sh#L5-L10

**Comment by GFrosi** [comment]
Thanks a lot!
